# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tidytuesday004',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tidytuesday004',
                'lib_path': 'tidytuesday004'},
  'syms': {'tidytuesday004.core': {'tidytuesday004.core.foo': ('core.html#foo', 'tidytuesday004/core.py')}}}
